baseURL = 'https://marcelino-portfolio.netlify.app/'
languageCode = 'en-us'
title = 'Marcelino Yax'
theme = "gokarna"

enableRobotsTXT = true

[params]
  footer = "Marcelino"
  avatarURL = "/images/marcelino-avatar.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-m"

  socialIcons = [
    {name = "twitter", url = "https://twitter.com/imarce7j"},
    {name = "linkedin", url = "https://www.linkedin.com/pub/marcelino-yax/b6/a4a/833gu"},
    {name = "github", url = "https://github.com/marceand"},
    {name = "email", url = "mailto:marce7j@gmail.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Resume"
    pre = "<span data-feather='user'></span>"
    url = "/about/resume"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/project"
    weight = 3

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 4
